import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  tokenLaunches: defineTable({
    tokenAddress: v.string(),
    tokenName: v.string(),
    tokenSymbol: v.string(),
    creatorAddress: v.string(),
    ownerAddress: v.string(),
    launchedByAddress: v.string(),
    chainId: v.number(),
    networkName: v.string(),
    totalSupply: v.string(),
    decimals: v.number(),
    launchStatus: v.string(),
    deployTxHash: v.union(v.string(), v.null()),
    tokenTransferTxHash: v.union(v.string(), v.null()),
    ownershipTransferTxHash: v.union(v.string(), v.null()),
    poolAddress: v.union(v.string(), v.null()),
    quoteTokenAddress: v.union(v.string(), v.null()),
    eventHubAddress: v.union(v.string(), v.null()),
    creatorAllocation: v.union(v.string(), v.null()),
    poolTokenAllocation: v.union(v.string(), v.null()),
    poolUsdtAllocation: v.union(v.string(), v.null()),
    initialPrice: v.union(v.string(), v.null()),
    launchTxHash: v.union(v.string(), v.null()),
    swapFeeBps: v.union(v.number(), v.null()),
    creatorFeeShareBps: v.union(v.number(), v.null()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_tokenAddress", ["tokenAddress"])
    .index("by_ownerAddress", ["ownerAddress"])
    .index("by_creatorAddress", ["creatorAddress"])
    .index("by_createdAt", ["createdAt"]),
  poolEvents: defineTable({
    chainId: v.number(),
    tokenAddress: v.string(),
    poolAddress: v.string(),
    eventType: v.string(),
    txHash: v.string(),
    logIndex: v.number(),
    blockNumber: v.number(),
    blockTimestamp: v.number(),
    trader: v.union(v.string(), v.null()),
    side: v.union(v.string(), v.null()),
    feeAsset: v.union(v.string(), v.null()),
    amountIn: v.union(v.string(), v.null()),
    amountOut: v.union(v.string(), v.null()),
    feeAmount: v.union(v.string(), v.null()),
    creatorFeeAmount: v.union(v.string(), v.null()),
    protocolFeeAmount: v.union(v.string(), v.null()),
    creatorFeesTotal: v.union(v.string(), v.null()),
    protocolFeesTotal: v.union(v.string(), v.null()),
    priceQuoteE18: v.union(v.string(), v.null()),
    reserveTokenAfter: v.union(v.string(), v.null()),
    reserveUsdtAfter: v.union(v.string(), v.null()),
    dataJson: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_txHash_logIndex", ["txHash", "logIndex"])
    .index("by_tokenAddress_blockNumber_logIndex", ["tokenAddress", "blockNumber", "logIndex"])
    .index("by_poolAddress_blockNumber_logIndex", ["poolAddress", "blockNumber", "logIndex"]),
  tokenCandles: defineTable({
    tokenAddress: v.string(),
    interval: v.string(),
    bucketStart: v.number(),
    open: v.string(),
    high: v.string(),
    low: v.string(),
    close: v.string(),
    volumeToken: v.string(),
    volumeQuote: v.string(),
    tradeCount: v.number(),
    updatedAt: v.number(),
  }).index("by_tokenAddress_interval_bucketStart", ["tokenAddress", "interval", "bucketStart"]),
  tokenStats: defineTable({
    tokenAddress: v.string(),
    latestPrice: v.string(),
    liquidityQuote: v.string(),
    reserveToken: v.string(),
    reserveQuote: v.string(),
    totalVolumeQuote: v.string(),
    volume24hQuote: v.string(),
    lastTradeAt: v.union(v.number(), v.null()),
    tradeCount: v.number(),
    updatedAt: v.number(),
  }).index("by_tokenAddress", ["tokenAddress"]),
  indexerState: defineTable({
    key: v.string(),
    lastSyncedBlock: v.number(),
    updatedAt: v.number(),
  }).index("by_key", ["key"]),
  chatThreads: defineTable({
    walletAddress: v.string(),
    title: v.string(),
    lastMessageAt: v.number(),
    createdAt: v.number(),
  }).index("by_walletAddress_lastMessageAt", ["walletAddress", "lastMessageAt"]),
  chatMessages: defineTable({
    threadId: v.id("chatThreads"),
    walletAddress: v.string(),
    role: v.string(),
    content: v.string(),
    actionsJson: v.string(),
    requestId: v.union(v.string(), v.null()),
    createdAt: v.number(),
  }).index("by_threadId_createdAt", ["threadId", "createdAt"]),
});
