import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  tokenLaunches: defineTable({
    tokenAddress: v.string(),
    tokenName: v.string(),
    tokenSymbol: v.string(),
    creatorAddress: v.optional(v.string()),
    ownerAddress: v.string(),
    launchedByAddress: v.string(),
    chainId: v.number(),
    networkName: v.string(),
    totalSupply: v.string(),
    decimals: v.number(),
    launchStatus: v.string(),
    deployTxHash: v.optional(v.union(v.string(), v.null())),
    tokenTransferTxHash: v.optional(v.union(v.string(), v.null())),
    ownershipTransferTxHash: v.optional(v.union(v.string(), v.null())),
    poolAddress: v.optional(v.union(v.string(), v.null())),
    quoteTokenAddress: v.optional(v.union(v.string(), v.null())),
    eventHubAddress: v.optional(v.union(v.string(), v.null())),
    creatorAllocation: v.optional(v.union(v.string(), v.null())),
    poolTokenAllocation: v.optional(v.union(v.string(), v.null())),
    poolUsdtAllocation: v.optional(v.union(v.string(), v.null())),
    initialPrice: v.optional(v.union(v.string(), v.null())),
    launchTxHash: v.optional(v.union(v.string(), v.null())),
    swapFeeBps: v.optional(v.union(v.number(), v.null())),
    creatorFeeShareBps: v.optional(v.union(v.number(), v.null())),
    createdAt: v.number(),
    updatedAt: v.optional(v.number()),
  })
    .index("by_tokenAddress", ["tokenAddress"])
    .index("by_ownerAddress", ["ownerAddress"])
    .index("by_creatorAddress", ["creatorAddress"])
    .index("by_createdAt", ["createdAt"]),
  poolEvents: defineTable({
    chainId: v.number(),
    tokenAddress: v.string(),
    poolAddress: v.string(),
    eventType: v.string(),
    txHash: v.string(),
    logIndex: v.number(),
    blockNumber: v.number(),
    blockTimestamp: v.number(),
    trader: v.union(v.string(), v.null()),
    side: v.union(v.string(), v.null()),
    feeAsset: v.union(v.string(), v.null()),
    amountIn: v.union(v.string(), v.null()),
    amountOut: v.union(v.string(), v.null()),
    feeAmount: v.union(v.string(), v.null()),
    creatorFeeAmount: v.union(v.string(), v.null()),
    protocolFeeAmount: v.union(v.string(), v.null()),
    creatorFeesTotal: v.union(v.string(), v.null()),
    protocolFeesTotal: v.union(v.string(), v.null()),
    priceQuoteE18: v.union(v.string(), v.null()),
    reserveTokenAfter: v.union(v.string(), v.null()),
    reserveUsdtAfter: v.union(v.string(), v.null()),
    dataJson: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_txHash_logIndex", ["txHash", "logIndex"])
    .index("by_tokenAddress_blockNumber_logIndex", ["tokenAddress", "blockNumber", "logIndex"])
    .index("by_poolAddress_blockNumber_logIndex", ["poolAddress", "blockNumber", "logIndex"]),
  tokenCandles: defineTable({
    tokenAddress: v.string(),
    interval: v.string(),
    bucketStart: v.number(),
    open: v.string(),
    high: v.string(),
    low: v.string(),
    close: v.string(),
    volumeToken: v.string(),
    volumeQuote: v.string(),
    tradeCount: v.number(),
    updatedAt: v.number(),
  }).index("by_tokenAddress_interval_bucketStart", ["tokenAddress", "interval", "bucketStart"]),
  tokenStats: defineTable({
    tokenAddress: v.string(),
    latestPrice: v.string(),
    liquidityQuote: v.string(),
    reserveToken: v.string(),
    reserveQuote: v.string(),
    totalVolumeQuote: v.string(),
    volume24hQuote: v.string(),
    lastTradeAt: v.union(v.number(), v.null()),
    tradeCount: v.number(),
    updatedAt: v.number(),
  }).index("by_tokenAddress", ["tokenAddress"]),
  indexerState: defineTable({
    key: v.string(),
    lastSyncedBlock: v.number(),
    updatedAt: v.number(),
  }).index("by_key", ["key"]),
  chatThreads: defineTable({
    walletAddress: v.string(),
    title: v.string(),
    lastMessageAt: v.number(),
    createdAt: v.number(),
  }).index("by_walletAddress_lastMessageAt", ["walletAddress", "lastMessageAt"]),
  chatMessages: defineTable({
    threadId: v.id("chatThreads"),
    walletAddress: v.string(),
    role: v.string(),
    content: v.string(),
    actionsJson: v.string(),
    requestId: v.union(v.string(), v.null()),
    createdAt: v.number(),
  }).index("by_threadId_createdAt", ["threadId", "createdAt"]),
  twitterBotConfigs: defineTable({
    walletAddress: v.string(),
    twitterHandle: v.string(),
    twitterHandleNormalized: v.string(),
    enabled: v.boolean(),
    lastSeenTweetId: v.union(v.string(), v.null()),
    lastSeenTweetAt: v.union(v.number(), v.null()),
    lastPolledAt: v.union(v.number(), v.null()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_walletAddress", ["walletAddress"])
    .index("by_enabled", ["enabled"])
    .index("by_twitterHandleNormalized", ["twitterHandleNormalized"]),
  twitterBotEvents: defineTable({
    configId: v.id("twitterBotConfigs"),
    walletAddress: v.string(),
    tweetId: v.string(),
    tweetUrl: v.union(v.string(), v.null()),
    tweetText: v.string(),
    tweetCreatedAt: v.union(v.number(), v.null()),
    targetHandle: v.string(),
    mentionMatched: v.boolean(),
    classifierStatus: v.string(),
    classifierConfidence: v.union(v.number(), v.null()),
    extractedTokenName: v.union(v.string(), v.null()),
    extractedTokenSymbol: v.union(v.string(), v.null()),
    launchStatus: v.string(),
    launchRecordId: v.union(v.string(), v.null()),
    errorMessage: v.union(v.string(), v.null()),
    providerPayloadJson: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_tweetId", ["tweetId"])
    .index("by_walletAddress_createdAt", ["walletAddress", "createdAt"])
    .index("by_configId_createdAt", ["configId", "createdAt"]),
});
